### ISSUE TITLE
Seg fault when build author is nil

### ISSUE THREAD

**Issue by patrobinson** [buildkite/cli#263]
I got the following seg fault:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x10144bfb4]

goroutine 78 [running]:
    github.com/buildkite/cli/v3/internal/build.buildCreator(...)
                                                                        /go/src/github.com/buildkite/cli/internal/build/view.go:33
                                                                                                                                  github.com/buildkite/cli/v3/internal/build.BuildSummary(0x140002141a0)
                                        /go/src/github.com/buildkite/cli/internal/build/view.go:16 +0x114
                                                                                                         github.com/buildkite/cli/v3/pkg/cmd/build.NewCmdBuildView.func1.2()
                /go/src/github.com/buildkite/cli/pkg/cmd/build/view.go:97 +0x338
                                                                                github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
                                                                                                                                                        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.1/tea.go:289 +0x34
                                                           created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1 in goroutine 75
                                                                                                                                                                /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.1/tea.go:288 +0x110
```

when running `bk build view <number> <pipeline>`

Running `3.0.0-beta.20240510`

https://github.com/buildkite/cli/blob/v3.0.0-beta.20240510/internal/build/view.go#L33

It seems likely Author can be nil here

**Comment by patrobinson** [comment]
I also built from source using the latest 3.x commit 31baea8138d0a3d34f3e57da2bfdcd3ef19f41d6 and it's still crashing
