### ISSUE TITLE
Specifying --pipeline option to init causes panic

### ISSUE THREAD

**Issue by irlevesque** [buildkite/cli#36]
CLI version: `0.3.0`
OS: Arch linux

```
→ bk init --pipeline=research
Checking for pipeline file: .buildkite/pipeline.yml ✅
Checking for git repository and remote: https://github.com/quantopian/research_env ✅
Enter passphrase to unlock /home/irl/.buildkite/keyring/: 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/buildkite/cli.InitCommand(0xa67ac0, 0xe56ae8, 0xa65020, 0xc00017dd70, 0x0, 0x0, 0x0, 0x7ffe0394a4e7, 0x8, 0x7f3124a12290, ...)
        /Users/lachlan/go/src/github.com/buildkite/cli/cmd_init.go:99 +0x1c5f
main.run.func5(0xc0001ea000, 0x409dc3, 0x936360)
        /Users/lachlan/go/src/github.com/buildkite/cli/cmd/bk/main.go:192 +0xb5
gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc0001b0498, 0xc0001ea000, 0x0, 0x0)
        /Users/lachlan/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/actions.go:28 +0x6d
gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc0001e4690, 0xc0001ea000, 0x0, 0x0)
        /Users/lachlan/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:557 +0xdf
gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc0001e4690, 0xc0001ea000, 0xc000176b50, 0x1, 0x1, 0x0, 0x0, 0x1, 0xc00019c2e8)
        /Users/lachlan/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:390 +0x8f
gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc0001e4690, 0xc0000a0010, 0x3, 0x3, 0x1, 0xc00019c2b8, 0x0, 0x1)
        /Users/lachlan/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:222 +0x1fa
main.run(0xc0000a0010, 0x3, 0x3, 0x9f9d88)
        /Users/lachlan/go/src/github.com/buildkite/cli/cmd/bk/main.go:356 +0x2a16
main.main()
        /Users/lachlan/go/src/github.com/buildkite/cli/cmd/bk/main.go:21 +0x6e
```

Without specifying pipeline:

```
→ bk init
Checking for pipeline file: .buildkite/pipeline.yml ✅
Checking for git repository and remote: https://github.com/quantopian/research_env ✅
Enter passphrase to unlock /home/irl/.buildkite/keyring/: 
Checking for buildkite pipeline: Created https://buildkite.com/quantopian/research-env ✅
Checking github repository config for quantopian/research_env: Created webhook ✅

Ok! Your project is ready to go at https://buildkite.com/quantopian/research-env 🚀
```

**Comment by mcncl** [comment]
I think this one can be closed with the v3 release, so I'm going to do that but invite it to be re-opened if the issue persists (we don't plan on supporting v2 going forward).
